
# vax_codes =  [
#   "FLU", "FLU6", "FLU8", "FL13", "H1N2", "H1N3", "H1N1", "HAV2", "HAV1", "HAV6", "HBV2",
#   "HBV1", "HPV2", "JEV", "MMR1", "MCV1", "MPV1", "PCV4", "PPV1", "IPV1", "RAB1", "ZOS",
#   "TDP1", "Td", "PPD1", "TWN2", "TWN1", "TYP", "VAR1", "YFV", "BCG", "FL11", "HAV4", "HBV3",
#   "HPV5", "MCV3", "MMR3", "PPV2", "TD4", "TDP4", "TWN3", "VAR4", "DT", "DTaP", "DTHI", "DTH",
#   "DHI", "DTI", "DTP", "DTP2", "FLU4", "FLU3", "FLU2", "FL10", "FLU9", "FLU7", "H1N7", "H1N5",
#   "H1N6", "H1N4", "HBHB", "HAV3", "HEPA", "HepB", "HIB2", "HPV6", "HPV", "IPV", "MMR", "MCV6",
#   "MCV4", "MCV5", "MCV7", "MPSV", "MMRV", "OPV", "PCV2", "PCV", "POL", "ROT1", "ROTA", "TD2",
#   "TDP2", "VAR2", "DTP3", "DTPz", "ENC", "FLUZ", "FLZ", "HPV3", "H1N8", "HAV", "HAV9", "HAV5",
#   "HBIG", "HBV9", "HBV5", "HBV4", "HBV6", "PRPO", "HIB3", "HbOC", "PRPT", "HIB4", "HIB5", "HIB",
#   "HPV4", "HPV9", "IG", "FL14", "FLU5", "MEA", "MMR9", "MERU", "MCV9", "MPM", "PCV9", "PPV9",
#   "PCV3", "IPVz", "IPV2", "MMR2", "TD3", "TDP3", "PPD2", "VAR3", "RAB2", "RIG", "ROT2", "Rub",
#   "S", "SPOX", "SMP", "TD5", "TDP9", "TD9", "PPD9", "PPD", "TWNz", "TYP2", "TYPH", "VAR9",
#   "VZIG", "Var"
# ]
vax_codes = {
  FLUZ: ["Flu, Preservative Free", "UNK", "1517"],
  HPV9: ["HPV, Quadrivalent, Gardasil", "MSD", "13429"],
  FLZ: ["Flu, unspecified", "UNK", "1514501"],
  MCV6: ["C-Meningococcal, Bexsero", "GSK", "148901A"],
  HepB: ["C-Hepatitis B Vaccine", "UNK", "237PJ"],
  HAV6: ["A-Hepatitis A Vaccine-Ped/adol", "UNK", "294X9"],
  HAV6: ["A-Hepatitis A Vaccine-Ped/adol", "SKB", "294X9"],
  HAV9: ["Hepatitis A Vaccine, Adult", "UNK", "2F559"],
  DTHI: ["C-DTaP/Hep B/IPV", "SKB", "2PY24"],
  HepB: ["C-Hepatitis B Vaccine", "SKB", "2XZ75"],
  FLU: ["A-Flu", "SKB", "3343R"],
  FL11: ["C-317 Adult Flu", "GSK", "37CC4"],
  FLU: ["A-Flu", "PMC", "397A7"],
  TWNz: ["Twinrix, HAV/HBV", "SKB", "3ED7N"],
  FL10: ["C-Flu Pres. Free (3-18 years)", "GSK", "3L9LD"],
  DTI: ["C-DTaP/IPV", "GSK", "3N7Y7"],
  DTI: ["C-DTaP/IPV", "SKB", "3N7Y7"],
  TWN1: ["A-Twinrix Travel Vaccine", "GSK", "3NK9A"],
  HAV3: ["C-Hepatitis A Vaccine (2 Dose)", "GSK", "3RB2G"],
  TDP9: ["Tdap", "UNK", "435P7"],
  HBV9: ["Hepatitis B Vaccine, Adult", "SKB", "45SJ2"],
  HepB: ["C-Hepatitis B Vaccine", "GSK", "475PE"],
  RAB1: ["A-Rabies Vaccine", "UNK", "550011A"],
  HBV3: ["C-317 Adult Hepatitis B", "GSK", "5G943"],
  TDP1: ["A-Td with Pertussis, Tdap", "GSK", "5MG55"],
  HAV1: ["A-Hepatitis A Vaccine", "GSK", "793JR"],
  TWN3: ["C-317 Adult Twinrix", "GSK", "925P2"],
  TDP2: ["C-Tdap", "GSK", "95L3P"],
  TDP9: ["Tdap", "SKB", "9N74F"],
  Td: ["A-Tetanus/Diptheria", "MBL", "A080A"],
  MCV5: ["C-Meningococcal, Menveo", "NOV", "A15009"],
  ROT1: ["C-Rotavirus (2 dose)", "GSK", "A41CB515A"],
  ROT1: ["C-Rotavirus (2 dose)", "UNK", "A41FB512A"],
  DTaP: ["C-DTaP", "GSK", "AC7AG"],
  DTHI: ["C-DTaP/Hep B/IPV", "GSK", "AE9JZ"],
  TD4: ["C-317 Adult Td", "SFP", "C4469AA"],
  Td: ["A-Tetanus/Diptheria", "SFP", "C4469AA"],
  PPD1: ["A-Tuberculin Skin Test", "SFP", "C4515AA"],
  PPD9: ["Tuberculin Skin Test", "SFP", "C4582AA"],
  TD2: ["C-Td 7+", "SFP", "C4736BA"],
  TD9: ["Tetanus, Diphtheria", "UNK", "C4736CA"],
  DTaP: ["C-DTaP", "UNK", "C4781AA"],
  DHI: ["C-DTaP/HIB/IPV", "PMC", "C4806AA"],
  DHI: ["C-DTaP/HIB/IPV", "SFP", "C4855AA"],
  HBV1: ["A-Hepatitis B Vaccine", "GSK", "F3BB3"],
  FLU7: ["C-Flumist (Live, Intranasal)", "MED", "FJ2099"],
  HAV4: ["C-317 Adult Hepatitis A", "MRK", "J007800"],
  HPV3: ["H-HPV Vaccine (HCF Grant)", "MRK", "J009788"],
  HAV4: ["C-317 Adult Hepatitis A", "GSK", "K002831"],
  ROTA: ["C-Rotavirus (3 dose)", "MRK", "K004773"],
  PPV2: ["C-317 Adult Pneumococcal PPV23", "MRK", "K008410"],
  PPV9: ["Pneumococcal Vaccine PPV23", "UNK", "K008410"],
  PCV9: ["Pneumococcal Conjugate, PCV13", "PFR", "K009874"],
  HPV5: ["C-317 Adult HPV", "MRK", "K010215"],
  HPV: ["C-HPV, Quad, Gardasil", "MRK", "K010215"],
  HBV3: ["C-317 Adult Hepatitis B", "MRK", "K010238"],
  MMR3: ["C-317 Adult MMR", "MRK", "K010318"],
  MMR: ["C-Measles, Mumps, Rubella", "MRK", "K010318"],
  MMR9: ["Measles, Mumps, Rubella", "UNK", "K010318"],
  VAR2: ["C-Varicella", "MRK", "K010337"],
  VAR9: ["Varicella Vaccine", "MSD", "K015971"],
  VAR4: ["C-317 Adult Varicella", "MRK", "K016129"],
  PPV1: ["A-Pneumococcal Vaccine PPV23", "MRK", "K019933"],
  HepB: ["C-Hepatitis B Vaccine", "MRK", "K026666"],
  POL: ["C-Polio (Unknown Type)", "UNK", "K1330"],
  IPV: ["C-IPV", "SFP", "K13301"],
  TYP: ["A-Typhoid Vaccine", "SFP", "K1536"],
  RAB1: ["A-Rabies Vaccine", "SFP", "K16133"],
  IPV1: ["A-Polio", "SFP", "K1694-1"],
  HAV3: ["C-Hepatitis A Vaccine (2 Dose)", "MRK", "L002717"],
  MMR1: ["A-Measles, Mumps, Rubella", "MRK", "L003855"],
  MMR9: ["Measles, Mumps, Rubella", "MSD", "L003859"],
  MMRV: ["C-MMR/Varicella", "MSD", "L007230"],
  PRPO: ["HIB Conjugate (Mening. Prot)", "UNK", "L009649"],
  PRPT: ["HIB polyrib. - Tetanus tox", "UNK", "L012838"],
  VAR1: ["A-Varicella Vaccine", "MRK", "L013063"],
  HPV6: ["C-HPV, 9", "MRK", "L013429"],
  HPV6: ["C-HPV, 9", "MSD", "L013429"],
  POL: ["C-Polio (Unknown Type)", "PMC", "L1001-1"],
  MCV7: ["C-Meningococcal, Trumenba", "PFR", "L13514"],
  PCV2: ["C-Pneumococcal Conjugate PCV13", "WA", "L53937"],
  PCV2: ["C-Pneumococcal Conjugate PCV13", "PFR", "L74252"],
  PCV: ["C-Pneumococcal Conjugate PCV7", "UNK", "LO1342B"],
  MCV9: ["Meningococcal, Menactra", "PMC", "LU5021AB"],
  RIG: ["Rabies Immune Globulin (RIG)", "UNK", "R1AD400051"],
  TD5: ["Td, Adult, preservative-free", "PMC", "U4669AA"],
  MCV3: ["C-317 Adult Meningococcal", "SFP", "U5020CA"],
  MCV4: ["C-Meningococcal, Menactra", "SFP", "U5082AB"],
  TDP4: ["C-317 Adult Tdap", "SFP", "U5095AA"],
  TDP2: ["C-Tdap", "SFP", "U5095AA"],
  FL10: ["C-Flu Pres. Free (3-18 years)", "SFP", "U5309BA"],
  FLU9: ["C-Flu Pres. Free (6-35 months)", "SFP", "U5319DA"],
  YFV: ["A-Yellow Fever Vaccine", "SFP", "UI106AA"],
  HIB2: ["C-HIB", "SFP", "UI149AAA"],
  FLU8: ["A-Flu High Dose (65+)", "PMC", "UI427AA"],
  FLU: ["A-Flu", "SFP", "UI441AD"],
  FLU6: ["A-Flu (preservative free)", "SFP", "UI445AA"],
  FL14: ["Influenza Virus, split, unspec", "UNK", "UI445AC"],
  FLU8: ["A-Flu High Dose (65+)", "SFP", "UI466AA"],
  FLU: ["A-Flu", nil, nil],
  DTP: ["C-DTP", nil, nil],
  FL10: ["C-Flu Pres. Free (3-18 years)", nil, nil],
  IPV: ["C-IPV", nil, nil],
  HPV6: ["C-HPV, 9", nil, nil],
  HAV6: ["A-Hepatitis A Vaccine-Ped/adol", "MSD", nil],
  HAV3: ["C-Hepatitis A Vaccine (2 Dose)", nil, nil],
  PPD1: ["A-Tuberculin Skin Test", nil, nil],
  FLUZ: ["Flu, Preservative Free", "SKB", nil],
  HAV5: ["Hepatitis A, unspecified", "UNK", nil],
  PRPO: ["HIB Conjugate (Mening. Prot)", "MSD", nil],
  TDP1: ["A-Td with Pertussis, Tdap", nil, nil],
  TWN1: ["A-Twinrix Travel Vaccine", nil, nil],
  VAR1: ["A-Varicella Vaccine", nil, nil],
  DTaP: ["C-DTaP", "SKB", nil],
  HIB2: ["C-HIB", nil, nil],
  HepB: ["C-Hepatitis B Vaccine", nil, nil],
  TD2: ["C-Td 7+", nil, nil],
  DTaP: ["C-DTaP", nil, nil],
  FLU6: ["A-Flu (preservative free)", nil, nil],
  TD5: ["Td, Adult, preservative-free", "UNK", nil],
  Td: ["A-Tetanus/Diptheria", nil, nil],
  FLU9: ["C-Flu Pres. Free (6-35 months)", nil, nil],
  PCV9: ["Pneumococcal Conjugate, PCV13", nil, nil],
  VAR2: ["C-Varicella", nil, nil],
  HBV6: ["Hepatitis B, unspecified", "UNK", nil],
  ROT1: ["C-Rotavirus (2 dose)", nil, nil],
  HepB: ["C-Hepatitis B Vaccine", "MSD", nil],
  FLZ: ["Flu, unspecified", "PMC", nil],
  HIB: ["HIB Unspecified", "UNK", nil],
  PCV2: ["C-Pneumococcal Conjugate PCV13", nil, nil],
  TDP2: ["C-Tdap", nil, nil],
  MMRV: ["C-MMR/Varicella", nil, nil],
  DTHI: ["C-DTaP/Hep B/IPV", nil, nil],
  MMR: ["C-Measles, Mumps, Rubella", nil, nil],
  PCV4: ["A-Pneumococcal Conjugate PCV13", nil, nil],
  PPD9: ["Tuberculin Skin Test", nil, nil],
  FLU7: ["C-Flumist (Live, Intranasal)", nil, nil],
  HAV1: ["A-Hepatitis A Vaccine", nil, nil],
  HBV1: ["A-Hepatitis B Vaccine", nil, nil],
  MMR1: ["A-Measles, Mumps, Rubella", nil, nil],
  H1N4: ["C-H1N1 Influenza Vaccine", "UNK", nil],
  ROT1: ["C-Rotavirus (2 dose)", "SKB", nil],
  HBIG: ["Hepatitis B Immune Globulin", nil, nil],
  HPV: ["C-HPV, Quad, Gardasil", nil, nil],
  ROT2: ["Rotavirus, unspecified", "UNK", nil],
  FLZ: ["Flu, unspecified", nil, nil],
  MCV4: ["C-Meningococcal, Menactra", nil, nil],
  ROTA: ["C-Rotavirus (3 dose)", nil, nil],
  DHI: ["C-DTaP/HIB/IPV", nil, nil]
}
